
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Mar 01 22:11:04 CET 2025
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 47;
  public static final int PR_INT = 14;
  public static final int POR = 8;
  public static final int CCIERRE = 35;
  public static final int PCIERRE = 13;
  public static final int PR_REAL = 15;
  public static final int CAP = 34;
  public static final int PUNTOCOMA = 41;
  public static final int DELETE = 32;
  public static final int WRITE = 25;
  public static final int MENORIGUAL = 49;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int IGUAL = 10;
  public static final int LLAP = 38;
  public static final int TYPE = 21;
  public static final int OR = 19;
  public static final int CALL = 42;
  public static final int DIV = 9;
  public static final int LLACIERRE = 39;
  public static final int IF = 22;
  public static final int AMPERSAND = 43;
  public static final int MAYORIGUAL = 48;
  public static final int EOF = 0;
  public static final int EVALUA = 2;
  public static final int DOBLEAMPERSAND = 51;
  public static final int TRUE = 28;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 37;
  public static final int MENOS = 7;
  public static final int MENOR = 46;
  public static final int NULL = 30;
  public static final int FARR = 52;
  public static final int PR_STRING = 17;
  public static final int MOD = 33;
  public static final int ASIGNACION = 44;
  public static final int MAYOR = 45;
  public static final int REAL = 5;
  public static final int ENT = 4;
  public static final int PAP = 12;
  public static final int ELSE = 23;
  public static final int PUNTO = 50;
  public static final int NL = 27;
  public static final int READ = 24;
  public static final int IDEN = 3;
  public static final int WHILE = 26;
  public static final int PROC = 40;
  public static final int PR_BOOL = 16;
  public static final int FALSE = 29;
  public static final int STRUCT = 36;
  public static final int MAS = 6;
}

