
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Mar 05 18:51:36 CET 2024
//----------------------------------------------------

package cup.asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 23;
  public static final int POR = 8;
  public static final int CCIERRE = 17;
  public static final int PCIERRE = 13;
  public static final int LCIERRE = 15;
  public static final int LAP = 14;
  public static final int PR_REAL = 44;
  public static final int CAP = 16;
  public static final int DELETE = 33;
  public static final int WRITE = 30;
  public static final int PUNCOMA = 25;
  public static final int NOT = 50;
  public static final int AND = 48;
  public static final int CIERREDECLARACION = 46;
  public static final int IGUAL = 10;
  public static final int TYPE = 51;
  public static final int OR = 49;
  public static final int CALL = 34;
  public static final int DIV = 9;
  public static final int IF = 26;
  public static final int AMPERSAND = 47;
  public static final int EOF = 0;
  public static final int ASIG = 18;
  public static final int EVALUA = 2;
  public static final int PR_ENT = 42;
  public static final int TRUE = 39;
  public static final int NEW = 32;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 38;
  public static final int MENOS = 7;
  public static final int NULL = 41;
  public static final int MENOR = 22;
  public static final int PR_STRING = 45;
  public static final int MOD = 35;
  public static final int REAL = 5;
  public static final int MAYOR = 21;
  public static final int POTENCIA = 36;
  public static final int ENT = 4;
  public static final int PAP = 12;
  public static final int ELSE = 27;
  public static final int PUNTO = 37;
  public static final int MAYORIG = 19;
  public static final int NL = 31;
  public static final int READ = 29;
  public static final int IDEN = 3;
  public static final int WHILE = 28;
  public static final int MENORIG = 20;
  public static final int PROC = 52;
  public static final int PR_BOOL = 43;
  public static final int FALSE = 40;
  public static final int STRUCT = 24;
  public static final int MAS = 6;
}

